### ISSUE TITLE
[VnV standalone]

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-planner#184]
Test plan stucked between planner and gatekeeper

![Capture](https://user-images.githubusercontent.com/16242967/69344260-5e3a3e80-0c6f-11ea-8fed-fd60879c70d7.PNG)

**Comment by santiagordguez** [comment]
@sinaure , which environment is this one?

Can you provide more info?

I'm retrieving info in graylog about all environments and no 14:50 trace is present in graylog:

![imagen](https://user-images.githubusercontent.com/15909508/69350201-65fee080-0c79-11ea-9f33-c40a01e495fa.png)

**Comment by sinaure** [comment]
we are using an EGM internal  env is out of the 5gtango list
it use an internal log stack

**Comment by santiagordguez** [comment]
It seems a configuration issue. 
If the problem persist, please reopen the issue.
