### ISSUE TITLE
Wrong coupling of TEST / NS

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-planner#187]
uploaded 1 couple of Test / NS
https://github.com/sonata-nfv/tng-tests/tree/master/tests/VnV/vnv-onboarding-phase

https://github.com/sonata-nfv/tng-tests/blob/master/packages/NSINDP1C/project.yml
https://github.com/sonata-nfv/tng-tests/blob/master/packages/TSTINDP/project.yml

The instantiation results in 2 test plans instead of one. 
tng-smpilot-ns1-emulator.eu.5gtango.0.1 has no reference to tag

  - "industrial-pilot-broker-egm"

so it should not be executed

test-industrial-pilot-ns1.eu.5gtango.egm.1.1 | tng-smpilot-ns1-emulator.eu.5gtango.0.1 | Wed, 11 Dec 2019 11:13:50 GMT | Scheduled |   |  
-- | -- | -- | -- | -- | --
test-industrial-pilot-ns1.eu.5gtango.egm.1.1 | tng-smpilot-ns1-k8s.eu.5gtango.0.1 | Wed, 11 Dec 2019 11:13:50 GMT | Scheduled

Can this be a package versioning related problem?

**Comment by santiagordguez** [comment]
did you check this tng-smpilot-ns1-emulator.eu.5gtango.0.1? 

![imagen](https://user-images.githubusercontent.com/15909508/70628424-6b23cf80-1c28-11ea-836b-d94f8247956b.png)

**Comment by santiagordguez** [comment]
As you can see, the testing tag matches with industrial-pilot-broker

tng-cli -u http://pre-int-vnv-bcn.5gtango.eu package -g 919f1e00-dc4b-458b-82d4-1b7d23ca2cfe

created_at: '2019-12-03T13:20:25.052+00:00'
md5: 2805e1115ed6dc0aa813ca9e6aa4736b
pd:
  description: 'Smart manufacturing pilot: Factory edge service (NS1) for vim-emu.'
  descriptor_schema: https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/package-specification/napd-schema.yml
  maintainer: Manuel Peuster (Paderborn University)
  name: tng-smpilot-ns1-emulator
  package_content:
  - algorithm: SHA-256
    content-type: application/vnd.5gtango.nsd
    hash: 944af29235557b08b7fe6d523b39dbd324be55892efe8ecba93b88dcb30c562b
    id:
      name: tng-smpilot-ns1-emulator
      vendor: eu.5gtango
      version: '0.1'
    source: Definitions/nsd/nsd_smpilot_ns1_emulator.yml
    tags:
    - eu.5gtango
    testing_tags:
    - industrial-pilot-broker
    uuid: b3c13392-4aca-46d6-af26-4f3700626d5f
  - algorithm: SHA-256
    content-type: application/vnd.5gtango.vnfd
    hash: ad7f25ed2ead3e0e7c61843f50d7f36162caeed09452d3c8a8bbbcf230ab9c88
    id:
      name: smpilot-cc
      vendor: eu.5gtango
      version: '0.1'
    source: Definitions/vnfd/vnfd_cc_emulator.yml
    tags:
    - eu.5gtango
    testing_tags: []
    uuid: 29cc281c-28a9-4c0c-bd54-a13e6aad4dc4
  - algorithm: SHA-256
    content-type: application/vnd.5gtango.vnfd
    hash: 175d3c460de2f6fb20d43cfe7f3d499b2b5ed3d2fc49d15ae41729b4f9341945
    id:
      name: smpilot-eae
      vendor: eu.5gtango
      version: '0.1'
    source: Definitions/vnfd/vnfd_eae_emulator.yml
    tags:
    - eu.5gtango
    testing_tags: []
    uuid: 2b69bfd4-c4a6-4d1d-8500-c46f388ca975
  package_file_name: eu.5gtango.tng-smpilot-ns1-emulator.0.1.tgo
  package_file_uuid: 9e3d8c5a-e63e-411a-918e-e07fae6efbc1
  package_type: application/vnd.5gtango.package.nsp
  release_date_time: '2019-09-19T12:22:00Z'
  vendor: eu.5gtango
  version: '0.1'
  warning: null
signature: null
status: active
updated_at: '2019-12-03T13:20:25.052+00:00'
username: ''
uuid: 919f1e00-dc4b-458b-82d4-1b7d23ca2cfe

**Comment by sinaure** [comment]
ok but this is the emulator test pd...
what is unclear is: every time there is a change in a package do I need to upgrade the version?
What happen if this is not removed?
@tsoenen

**Comment by santiagordguez** [comment]
It's a good practice to use versioning but in this case it doesn't solve the multiple pairs. As you mentioned, if you have several versions uploaded with the same testing tags they will produce multiple testing pairs

**Comment by tsoenen** [comment]
We can remove the emulator package, because on the VnV, everything is tested against the k8s package.

**Comment by sinaure** [comment]
done!
