### ISSUE TITLE
Validate generated plan before being scheduled

### ISSUE THREAD

**Issue by andreoug** [sonata-nfv/tng-vnv-planner#4]
According to Vigo meeting notes: "Validate generated plan before being scheduled"

**Comment by jbonnet** [comment]
This is the feature that allows the test developer to validate all plans generated for his/her test, before they're schedulled. The idea is is that (either) the package uploading should support an extra field like `validate_plans`, default to `false`, or the test descriptor with a similar field. After the generation of all the plans containning this test, these plans would not be immediately schedulled to be executed, but wait for a validation of the test developer. There would have to be an API selecting such test plans, the test developer should choose wich ones to keep and which to drop, and submit the list to the Planner. Only then these plans should be schedulled.

**Comment by andreoug** [comment]
@jbonnet 'validate' drive me more to the form field validation or an input object validation. anyway, `validate_plans` will be the new field for the callback and the test descriptor.

**Comment by jbonnet** [comment]
Which would be a better name, then? Note that it is **either** in the on-boarding package (impact on the whole process) **or** a field in the Test Descriptor (I'd prefer this one, local impact)

**Comment by andreoug** [comment]
"confirm required" as confirm_required, in both places, what you think?

**Comment by jbonnet** [comment]
be it! In the TD
