### ISSUE TITLE
Planner gets the next available test plan, when this is available. 

### ISSUE THREAD

**Issue by andreoug** [sonata-nfv/tng-vnv-planner#44]
Workflow manager checks for a new testPlan every 5000 millisec's. every unblobing of a null obj gives an exception to log records.

**Comment by jbonnet** [comment]
@allemaos why not having an event-driven architecture (push, instead of pool)?

**Comment by andreoug** [comment]
could you please explain, it is push to curator. what you think?

**Comment by jbonnet** [comment]
> ...it is push to curator

great! But you mentioned above that 

> Workflow manager checks for a new testPlan every 5000 millisec's...

this is a pull-based architecture (i.e., hard to define an optimal time interval for all cases); you could instead opt fora  push-based architecture: whenever a new plan comes, action is taken. This could be done (just an example) whith a trigger in the database: after you save a new package uuid, a piece of code is triggered and starts executing, fecthing the NSDs/TDs, etc.

**Comment by allemaos** [comment]
> > ...it is push to curator
> 
> great! But you mentioned above that
> 
> > Workflow manager checks for a new testPlan every 5000 millisec's...
> 
> this is a pull-based architecture (i.e., hard to define an optimal time interval for all cases); you could instead opt fora push-based architecture: whenever a new plan comes, action is taken. This could be done (just an example) whith a trigger in the database: after you save a new package uuid, a piece of code is triggered and starts executing, fecthing the NSDs/TDs, etc.

Push it is @jbonnet to curatror. isnt it? Planner.WorkflowManager triggers DB every 5sec and then if there is a testPlan it sends it to curator.

Check the code. Search for:  ` @Scheduled(fixedRate = 5000L , initialDelay = 1000L)`

??? is the push arch between DB and Planner.WorkflowManager using `stored procedure` in DB???

**Comment by andreoug** [comment]
@jbonnet I will close this issues as resolved and if you prefer to change the arch please let me know, please one a new issue.

**Comment by andreoug** [comment]
u r right. I closed and openned a new
