### ISSUE TITLE
Find TDs that match NSDs received in new packages

### ISSUE THREAD

**Issue by andreoug** [sonata-nfv/tng-vnv-planner#6]
According to Vigo meeting notes: "Find NSDs that match TDs received in new packages"

**Comment by andreoug** [comment]
In this task we have been asked for the tagged paired Test's for a specific NetworkService. But there is no such and endpoint for this in Catalog. So in the AS-IS, we use two step to extract our list of Test:

- i) We find the Networkservice for this uuid (search4 `List<TestSuiteOld> findTssByNetworkServiceUUid(String uuid)`) and then 
- ii) we list the tags of the resulted NetworkService and then iteratively  
- iii) we find the list of Tests for each tag (search4 `List<TestSuiteOld> findTssByTestTag(String tag)`)

So, we need to review and unitest the AS-IS (with our current Catalog mocked endpoints).

**Comment by jbonnet** [comment]
@allemaos remember we have this API ready from the Catalogue, so ii) and iii) might not make sense

**Comment by andreoug** [comment]
I think that we dont have it ready. :(

@panstav1 is this API call ready from Catalog?
https://github.com/sonata-nfv/tng-cat/wiki/General-Description-of-Catalogues-API

**Comment by jbonnet** [comment]
we had this conversation before...

**Comment by panstav1** [comment]
@jbonnet @allemaos Not once, but we had this conversation several times :) 

In the Catalogues, I have implemented the full-text search. You can query the Catalogue with attributes. Equivalently, you can query NSDs with the test tag and TD with the corresponding test tag. Catalogues are the API of the DB, thus meant for queries. Every time we had this conversation, we agreed to implement the intelligence of "i have a NSD, get me the corresponding test descriptors" **on top of the Catalogues**. This means not to have this API in the Catalogues. Eventually, this is reasonable as this request is equal to 2 queries in the Catalogues

**Comment by andreoug** [comment]
Let me mention the current status.

According to the [new proposed Test Descriptor](https://github.com/sonata-nfv/tng-schema/blob/master/test-descriptor/examples/test-descriptor-example.yml) the tagging in Test Descriptor are as follows:
```
test_tags:
  - rtmp-media-service
```

From the other side the current [Media Pilot NS Descriptor](https://github.com/sonata-nfv/tng-media-pilot/blob/master/mediapilot-service/Definitions/mediapilot-ns.yml) the tagging is as follows:
```
testing_tags: 
  - http
```

**Comment by andreoug** [comment]
@jbonnet I think that, according to the change for the new implementation is that Planner endpoint will be the full NSD, the i) will already be covered. 

According to this, the only step we need is the queries to Catalog will be the iteration of the tags. But again this is `Tag Based Query` and not `NSD Based Query`. 

so we know what we want from Catalog. If we clarify what is the body of the request, we can proceed with this issue.

**Comment by jbonnet** [comment]
@allemaos No, you can grab all NSDs with `...?testing_tags=http` and all TDs with `...?test_tags=rtmp-media-service`. With these two sets you can build all plans needed.

**Comment by andreoug** [comment]
@jbonnet no? this is what I said. we are saying the same thing.

I have talked with panos.
1NS -> 1..many tags -> 1 query with OR between tags (@panstav1 has already developed this)
@panstav1 could you send me plz the query syntax with OR?

**Comment by andreoug** [comment]
@sinaure The feature is "Find TDs that match NSDs received in new packages", which means:  

While Planner gets new packages (test case `CatalogueCallbackControllerTest`), 
the Planner will ask from Catalogue (in this new V&V version) all the tagged matching TD's of the NSD.  Planner will get the tags of one or many NSD's and populate the TD's that have the same tag with the NSD. 

This can break three tests: 
- "Find the TD's from 1 NSD with out tag" 
- "Find the TD's from 1 NSD with multiple tag's" 
- "Find the TD's from many NSD's" 

The use of catalog mock will provide the matched TD's according to the tags of NSD.

Note: The `"retrieval of a list of NetworkServices whith tag existing on tags list" testing` was from the previous implementation, where the Planner(LCM) requested all the NServicesDescr's and the TestDescr's from Catalogue. This functionality will transferred to catalogue (tng-cat).. 

The 
1. scaffold the tests, 
2. find the implemented source code, review it,  and prepare the tests (almost tdd) 
3. complete tests, mocks, json files. 
4. if the source is not functional, fix the bugs.

**Comment by sinaure** [comment]
@panstav Can I assume the catalog api with query params are looking for nested fields?
curl -H "Content-Type: application/json" http://pre-int-vnv-bcn.5gtango.eu:401 1/api/catalogues/v2/network-services?**nsd.testing_tags**=latency


I was looking here but I was not sure: 
https://github.com/sonata-nfv/tng-cat/blob/master/routes/catalogue_nsd.rb

the nsd.testing_tags is of type array  how can we search if a tag is contained in that array (not sure this logic is availablo neither)
 
@allemaos 
in Catalogue all the endpoint points to GK are we going to point all to catalog instead? 

@Value('${app.gk.service.metadata.endpoint}')
    def serviceMetadataEndpoint

**Comment by andreoug** [comment]
"@allemaos
in Catalogue all the endpoint points to GK are we going to point all to catalog instead?"

Planner talks to Catalogue through GK and it will still work like that. I think that the reason is that Catalogue could be anywhere in the network and need to be protected.

**Comment by andreoug** [comment]
this issue also refers to planner package upload callback functionality. 
after @sinaure updates on get call with url param. we need only updated unit tests

**Comment by andreoug** [comment]
with https://github.com/sonata-nfv/tng-vnv-planner/pull/20 PR this issue is sorted
