### ISSUE TITLE
Network Service Controller If service not found error 500

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-planner#87]
curl -X GET "http://pre-int-vnv-bcn.5gtango.eu:6100/api/v1/test-plans/services/idNotExisting56767785HGFHDF7656/tests" -H "accept: */*"

Swagger return a 500 error with a 404 message. Error handling should rather return an empty array

{
  "timestamp": 1555683309972,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.web.client.HttpClientErrorException",
  "message": "404 Not Found",
  "path": "/api/v1/test-plans/services/362b0f71-7b3f-41f5-8699-1319cb9ebb76/tests"
}

curl -X GET "http://pre-int-vnv-bcn.5gtango.eu:6100/api/v1/test-plans/services/6ee5f38c-c0e2-422a-8f27-9ecf8189bdc8/tests" -H "accept: */*"

return code 200 
[]

If service not found should not cause an internal server error

**Comment by andreoug** [comment]
lets catch these exceptions
