### ISSUE TITLE
update test-plans CRUD

### ISSUE THREAD

**Issue by andreoug** [sonata-nfv/tng-vnv-planner#99]
/test-plans/ endpoint's CRUD will: read 1 testPlan, delete 1 testPlan, create Many testPlan's, update Many testPlan's

**Comment by jbonnet** [comment]
@allemaos Usually

1. POSTs (create) create one
1. PUTs (update) update one

Is there a strong reason why we need to change this standard behaviour?

**Comment by andreoug** [comment]
@jbonnet  this is what the group asked and I followed. 
IMHO, it should be two different endpoints for two different objects
CRUD testPlan and 
CRUD testPlanList, where for the testPlanList we could use testSuite param or any other

**Comment by jbonnet** [comment]
@allemaos no one, I'm sure, have asked you that. I don't know what the `.../testPlanList`endpoint does. It's CRUD on one resource, `test-plans`.

**Comment by andreoug** [comment]
:S @jbonnet, I always ask for confirmation. 
np, I will update the endpoint.

**Comment by andreoug** [comment]
@jbonnet also you said also for **sort the test-plans according to index field**. how can you sort for the execution test-plans? in each insert we will resport the full list of testplans already scheculed test-plans that are not already in "STARTING" status?

**Comment by jbonnet** [comment]
@allemaos 

> sort the test-plans according to index field...

we need to sort them in some form. I think it'll work if by default you sort them by the update date (older plan first). If we want to give the test owner the possibility of changing the order of **his**/**her** tests, we'll have to think about it

> ...in each insert we will resport the full list of testplans already scheculed test-plans that are not already in "STARTING" status?

didn't get it, sorry. If I understood your words correctely, the full list should be requested specifically, and not simply returned after each insert

**Comment by andreoug** [comment]
> @allemaos
> 
> > sort the test-plans according to index field...
> 
> we need to sort them in some form. I think it'll work if by default you sort them by the update date (older plan first). If we want to give the test owner the possibility of changing the order of **his**/**her** tests, we'll have to think about it

We could/would have a client side impl and backend wont sort. You know better. 

> 
> > ...in each insert we will resport the full list of testplans already scheculed test-plans that are not already in "STARTING" status?
> 
> didn't get it, sorry. If I understood your words correctely, the full list should be requested specifically, and not simply returned after each insert

No, my fault. no worries. This feature with POST or PUT listOfTestPlans is closed.  

we have the cleint side approach or/and the backend db query. I think it's solved :)
